> #### let / var / const

- 块级作用域
- 暂时性死区
- const 声明变量不能改变，如果声明的是一个引用类型，则不能改变它的内存地址

> #### 常用 ES6

- Let 与 Const
- 类
- 模块化
- 箭头函数
- 函数参数默认值
- 模板字符串
- 解构赋值
- 延展操作符
- 对象属性简写
- Promise

> #### 箭头函数

1. 箭头函数没有 arguments（建议使用更好的语法，剩余运算符替代）

2) 箭头函数没有 prototype 属性，不能用作构造函数（不能用 new 关键字调用）

3. 箭头函数没有自己 this，它的 this 是词法的，引用的是上下文的 this，即在你写这行代码的时候就箭头函数的 this 就已经和外层执行上下文的 this 绑定了(这里个人认为并不代表完全是静态的,因为外层的上下文仍是动态的可以使用 call,apply,bind 修改,这里只是说明了箭头函数的 this 始终等于它上层上下文中的 this)

4. 箭头函数的 this 指向即使使用 call,apply,bind 也无法改变（这里也验证了为什么 ECMAScript 规定不能使用箭头函数作为构造函数，因为它的 this 已经确定好了无法改变）

> #### 扩展运算符`...`

<img src="imgs/Spread_Operator.png" />

> #### 对象属性/方法简写

es6 允许当对象的属性和值相同时，省略属性名

<img src="imgs/es6_01.png" />

- 省略的是属性名而不是值
- 值必须是一个变量

对象属性简写经常与解构赋值一起使用

<img src="imgs/es6_02.png" />

es6 允许当一个对象的属性的值是一个函数（即是一个方法），可以使用简写的形式

<img src="imgs/es6_03.png" />



> #### 手写 Promise

```js
var myPromise = new Promise((resolve, reject) => {
  // 需要执行的代码
  ...
  if (/* 异步执行成功 */) {
    resolve(value)
  } else if (/* 异步执行失败 */) {
    reject(error)
  }
})

myPromise.then((value) => {
  // 成功后调用, 使用value值
}, (error) => {
  // 失败后调用, 获取错误信息error
})
```

> #### 描述一下 Promise

Promise 是一个对象，它代表了一个异步操作的最终完成或者失败。由于它的 then 方法和 catch、finally 方法会返回一个新的 Promise 所以可以允许我们链式调用，解决了传统的回调地狱问题。
再说一下 then 以及 catch 方法：

1. Promise 的`状态`一经改变就不能再改变。
2. `.then` 和`.catch` 都会返回一个新的 Promise。
3. `catch` 不管被连接到哪里，都能捕获上层未捕捉过的错误。
4. 在 Promise 中，返回任意一个非 promise 的值都会被包裹成 `promise 对象`，例如 return 2 会被包装为 return Promise.resolve(2)。
5. Promise 的 .then 或者 .catch `可以被调用多次`, 但如果 Promise 内部的`状态一经改变`，并且有了一个值，那么后续每次调用.then 或者. catch 的时候都会`直接拿到该值`。
6. .then 或者 .catch 中 return 一个 `error 对象`并不会抛出错误，所以不会被后续的 .catch 捕获。
7. .then 或 .catch 返回的值`不能是 promise 本身`，否则会造成死循环。
8. .then 或者 .catch 的参数期望是`函数`，传入非函数则会发生值透传。
9. .then 方法是能接收两个参数的，第一个是`处理成功的函数`，第二个是`处理失败的函数`，再某些时候你可以认为 catch 是.then 第二个参数的简便写法。
10. `.finally` 方法也是返回一个 Promise，他在 Promise 结束的时候，无论结果为 resolved 还是 rejected，都会执行里面的回调函数。

另外也可以说一下 finally 方法：

- .finally()方法不管 Promise 对象最后的状态如何都会执行

- .finally()方法的回调函数不接受任何的参数，也就是说你在.finally()函数中是没法知道 Promise 最终的状态是 resolved 还是 rejected 的

- 它最终返回的默认会是一个上一次的 Promise 对象值，不过如果抛出的是一个异常则返回异常的 Promise 对象。

最后可以说一下 `all` 以及 `race` 方法：

- Promise.all()的作用是接收一组异步任务，然后并行执行异步任务，并且在`所有异步操作执行完`后才执行回调。
- .race()的作用也是接收一组异步任务，然后并行执行异步任务，只保留取`第一个执行完成的异步操作的结果`，其他的方法仍在执行，不过执行结果会被抛弃。
- Promise.all().then()结果中数组的顺序和 Promise.all()接收到的数组顺序一致。
- all 和 race 传入的数组中如果有会抛出异常的异步任务，那么只有最先抛出的错误会被捕获，并且是被 then 的第二个参数或者后面的 catch 捕获；但并不会影响数组中其它的异步任务的执行。

> #### async / await

> #### Proxy

> #### Object.definePropery
